#!/bin/bash
[ $# -eq 0 ] && { echo; echo "Usage: wrap [-x] command [args]"; echo; exit 1; }
Home="/Users/`whoami`"
if [ "$1" == "-x" ]; then
    Target="$2"
    workingD=`pwd`
    if [[ ${workingD} != *"`whoami`"* ]];then
        echo&&echo "Wrap must be run within your home directory tree (/Users/`whoami`/*)"
        echo&&exit
    fi    
    wdIn="${workingD// /\\ }"
    Command="$Target ${@:3}"
    Command=${Command/~/$Home}
    screen -dmS $Target bash -c "docker exec -i -t wrappers bash -c '(cd $wdIn && $Command)' && exit"
elif [ "$1" == "bash" ]; then
    locCheck=`pwd`
    if [[ ${locCheck} != *"`whoami`"* ]];then
        echo&&echo "Wrap must be run within your home directory tree (/Users/`whoami`/*)"
        echo&&exit
    fi
    Command="$1"
    workingD="`pwd|cut -d'/' -f 4-`"
    if [ -z "$workingD" ]; then
        workingD="/Users/`whoami`/"
    else
        workingD="/Users/`whoami`/$workingD"
    fi
    wdIn="${workingD// /\\ }"
    docker exec -i -t wrappers bash -c "(cd $wdIn && banner && $Command)" && wrap clear
elif [ "$1" == "tcsh" ] || [ "$1" == "csh" ]; then
    locCheck=`pwd`
    if [[ ${locCheck} != *"`whoami`"* ]];then
        echo&&echo "Wrap must be run within your home directory tree (/Users/`whoami`/*)"
        echo&&exit
    fi
    Command="tcsh"
    workingD="`pwd|cut -d'/' -f 4-`"
    if [ -z "$workingD" ]; then
        workingD="/Users/`whoami`/"
    else
        workingD="/Users/`whoami`/$workingD"
    fi
    wdIn="${workingD// /\\ }"
    docker exec -i -t wrappers bash -c "(cd $wdIn && banner && $Command)" && wrap clear
elif [ "$1" == "start-edit" ]; then 
    declare -a OPS=(Apt Python Exit)
    declare -a ACTS=(Add/Remove Search/List Cancel)
    op=""
    act=""
    bold=$(tput bold)
    normal=$(tput sgr0)
    echo&&echo "${bold}Select a package type (Apt or Python):${normal}"&&echo
    select op in "${OPS[@]}"; do
      [[ -n $op ]] || { echo&&echo "${bold}Invalid selection. Please try again:${normal}"&&echo >&2; continue; }
      break #
    done

    if [ "$op" == "Exit" ]; then
      echo&&exit
    fi

    echo&&echo "${bold}What to do?${normal}"&&echo
    select act in "${ACTS[@]}"; do
      [[ -n $act ]] || { echo&&echo "${bold}Invalid selection. Please try again:${normal}"&&echo >&2; continue; }
      break #
    done

    if [ "$act" == "Cancel" ]; then
      wrap start-edit
    elif [ "$op" == "Apt" ]; then
      if [ "$act" == "Search/List" ]; then
        echo&&echo -n "${bold}Enter a search pattern:${normal} " && read searchPat
        echo && wrap apt-cache search "$searchPat" \| cut \-d\' \' \-f1 \| more
        wrap start-edit
      elif [ "$act" == "Add/Remove" ]; then
        wrap nano \/root\/.installPackages&&clear
      fi
    else
      if [ "$act" == "Search/List" ]; then
        echo&&echo -n "${bold}Enter a search pattern:${normal} " && read searchPat
        echo && wrap wget \-O \- \-q https\:\/\/pypi.org\/simple\/ \| grep \-i "$searchPat"\|cut \-d'/' \-f3\|more
        wrap start-edit
      elif [ "$act" == "Add/Remove" ]; then
        wrap nano \/root\/.installPip&&clear
      fi
    fi
    exit
else
    Target="$1"
    workingD="`pwd`"
    if [[ ${workingD} != *"`whoami`"* ]];then
        echo&&echo "Wrap must be run within your home directory tree (/Users/`whoami`/*)" 
        echo&&exit
    fi
    wdIn="${workingD// /\\ }"
    Command="$Target ${@:2}"
    Command=${Command/~/$Home}
    docker exec -i -t wrappers bash -c "(cd $wdIn && $Command)"
    exit
fi
exit
