#!/bin/bash
[ $# -eq 0 ] && { echo; echo "Usage: wrap [-x] command [args]"; echo; exit 1; }
Home="/Users/`whoami`"
if [ "$1" == "-x" ]; then
    Target="$2"
    workingD=`pwd`
    if [[ ${workingD} != *"`whoami`"* ]];then
        echo&&echo "Wrap must be run within your home directory tree (/Users/`whoami`/*)"
        echo&&exit
    fi    
    wdIn="${workingD// /\\ }"
    Command="$Target ${@:3}"
    Command=${Command/~/$Home}
    screen -dmS $Target bash -c "docker exec -i -t wrappers bash -c '(cd $wdIn && $Command)' && exit"
elif [ "$1" == "bash" ]; then
    locCheck=`pwd`
    if [[ ${locCheck} != *"`whoami`"* ]];then
        echo&&echo "Wrap must be run within your home directory tree (/Users/`whoami`/*)"
        echo&&exit
    fi
    Command="$1"
    workingD="`pwd|cut -d'/' -f 4-`"
    if [ -z "$workingD" ]; then
        workingD="/Users/`whoami`/"
    else
        workingD="/Users/`whoami`/$workingD"
    fi
    wdIn="${workingD// /\\ }"
    docker exec -i -t wrappers bash -c "(cd $wdIn && banner && $Command)" && clear
elif [ "$1" == "tcsh" ] || [ "$1" == "csh" ]; then
    locCheck=`pwd`
    if [[ ${locCheck} != *"`whoami`"* ]];then
        echo&&echo "Wrap must be run within your home directory tree (/Users/`whoami`/*)"
        echo&&exit
    fi
    Command="tcsh"
    workingD="`pwd|cut -d'/' -f 4-`"
    if [ -z "$workingD" ]; then
        workingD="/Users/`whoami`/"
    else
        workingD="/Users/`whoami`/$workingD"
    fi
    wdIn="${workingD// /\\ }"
    docker exec -i -t wrappers bash -c "(cd $wdIn && banner && $Command)" && clear
else
    Target="$1"
    workingD="`pwd`"
    if [[ ${workingD} != *"`whoami`"* ]];then
        echo&&echo "Wrap must be run within your home directory tree (/Users/`whoami`/*)" 
        echo&&exit
    fi
    wdIn="${workingD// /\\ }"
    Command="$Target ${@:2}"
    Command=${Command/~/$Home}
    docker exec -i -t wrappers bash -c "(cd $wdIn && $Command)"
    exit
fi
exit
